FROM node:22-alpine AS base


FROM base AS deps

WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci


FROM base as dev

WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .



FROM base as builder

WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

RUN npm run build


FROM base as runner

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 remix

WORKDIR /app
COPY --from=builder /app/build ./

USER remix
CMD ["npm", "remix-serve", "build/server/index.js"]
